# Generated by Django 4.0.4 on 2022-05-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'subsidaries',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('subsidary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.subsidary')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.ward')),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.ward')),
            ],
            options={
                'db_table': 'neighborhoods',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subsidary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.subsidary')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
