# Generated by Django 4.0.4 on 2022-05-03 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menu_created_at_alter_restaurant_created_at_and_more'),
        ('restaurants', '0003_alter_menu_updated_at_alter_restaurant_updated_at_and_more'),
    ]

    operations = [
    ]
