# Generated by Django 4.0.4 on 2022-05-06 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_name_restaurant_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='메뉴 이름'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='메뉴 가격'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='subsidary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.subsidary', verbose_name='프랜차이즈 업종'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=10, verbose_name='행정구역(동)'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.ward', verbose_name='행정 구역(구) FK'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='지점 이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='store',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='n호점'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='subsidary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.subsidary', verbose_name='프랜차이즈 업종'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.ward', verbose_name='행정 구역(구) FK'),
        ),
        migrations.AlterField(
            model_name='subsidary',
            name='name',
            field=models.CharField(max_length=20, verbose_name='프랜차이즈 이름'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=10, verbose_name='행정 구역(시,구)'),
        ),
    ]
